/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-02-22 02:34:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<title>App42 Sample Java-MySql Application</title>\n");
      out.write("<link href=\"css/style-User-Input-Form.css\" rel=\"stylesheet\"\n");
      out.write("\ttype=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.6.4.js\"></script>\n");
      out.write("</head>\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\t\t$('#SubmitButton').click(function() {\n");
      out.write("\t\t\t//$(\"#contactPersonErr\").hide();\n");
      out.write("\t\t\tvar error = \"false\";\n");
      out.write("\t\t\t$(\"#contactPersonErr\").hide();\n");
      out.write("\t\t\t$(\"#emailErr\").hide();\n");
      out.write("\t\t\tif ($.trim($(\"#contactPerson\").val()).length == 0) {\n");
      out.write("\t\t\t\t$(\"#contactPersonErr\").show();\n");
      out.write("\t\t\t\terror = \"true\";\n");
      out.write("\t\t\t}if ($.trim($(\"#email\").val()).length == 0) {\n");
      out.write("\t\t\t\t$(\"#emailErr\").show();\n");
      out.write("\t\t\t\terror = \"true\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (error == \"true\") {\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\treturn true;\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"App42PaaS_header_wrapper\">\n");
      out.write("\t\t<div class=\"App42PaaS_header_inner\">\n");
      out.write("\t\t\t<div class=\"App42PaaS_header\">\n");
      out.write("\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t<a href=\"http://paas.shephertz.com\"><img border=\"0\"\n");
      out.write("\t\t\t\t\t\talt=\"App42PaaS\" src=\"images/logo.png\"></img></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!------------------------------------Header Closed------------------------------------------->\n");
      out.write("\t<div class=\"App42PaaS_body_wrapper\">\n");
      out.write("\t\t<div class=\"App42PaaS_body\">\n");
      out.write("\t\t\t<div class=\"App42PaaS_body_inner\">\n");
      out.write("\t\t\t\t<div class=\"contactPage_title\">User Input Form</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form_wrapper\">\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"save\">\n");
      out.write("\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t<legend>Personal Particular</legend>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contactForm_tr\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contactForm_td1\">Name</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contactForm_tdMiddle\">:</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contactForm_td2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"name\" type=\"text\" class=\"Personal-input\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"contactPerson\" value=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contactForm_td2\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red; padding-left: 90px; display: none;\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"contactPersonErr\">Name is mandatory</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contactForm_tr\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contactForm_td1\">Email</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contactForm_tdMiddle\">:</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contactForm_td2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"email\" type=\"text\" id=\"email\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"Personal-input\" maxlength=\"30\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contactForm_td2\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red; padding-left: 90px; display: none;\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"emailErr\">Email is mandatory</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t<fieldset>\n");
      out.write("\t\t\t\t\t\t\t<legend>What do you like about this Page :</legend>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"massage-box\">\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"description\" cols=\"30\" rows=\"5\" id=\"description\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"massage-textFild\">Enter your instruction here...</textarea>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</fieldset>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-button\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-left: 100px; margin-right: 10px;\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"SubmitButton\" class=\"submit_btn\" type=\"image\" border=\"0\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"submit\" alt=\"Submit\" src=\"images/submit_btn.png\"></input>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-button\">\n");
      out.write("\t\t\t\t\t\t\t<input id=\"Submit\" class=\"clear_btn\" type=\"image\" border=\"0\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"clear\" alt=\"clear\" src=\"images/clear_btn.png\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"reachus_wrapper\">\n");
      out.write("\t\t\t\t\t<div class=\"reach_icon\">\n");
      out.write("\t\t\t\t\t\t<img border=\"0\" alt=\"REACH US AT\" src=\"images/reach_icon.png\"></img>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"reach_txt\">\n");
      out.write("\t\t\t\t\t\t<div class=\"reachusTitle\">REACH US AT:</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"reachuslable\">Sales Enquiries:</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"reachusLink\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mailto:sales@shephertz.com\">sales@shephertz.com</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"reachuslable\">Feedback:</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"reachusLink\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mailto:feedback@shephertz.com\">feedback@shephertz.com</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"reachuslable\">Customer Support:</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"reachusLink\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mailto:support@shephertz.com\">support@shephertz.com</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"reachus_wrapper_vcard\">\n");
      out.write("\t\t\t\t\t<div class=\"vcard_txt\">ShepHertz Technologies Pvt. Ltd. Spaze\n");
      out.write("\t\t\t\t\t\tI-Tech Park, Tower-A, 11th floor - 1128, sector-49, Sohna Road,\n");
      out.write("\t\t\t\t\t\tGurgaon - 122001 INDIA</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
